### PR TITLE
Add travis-ci config

### PR DESCRIPTION
**Pull request by sanemat**
Would you set travis-ci?

### CODE REVIEW

**Comment by jgrevich** [comment]
:+1: can you update with the latest rubies and rebase your commit?

**Comment by sanemat** [comment]
@jgrevich I added ruby 2.1.2 and squashed, done:bowtie:

**Comment by jgrevich** [comment]
Awesome @sanemat !  Now we need to get these PRs pushed through :) @yourewelcome @MitinPavel what do you think?

**Comment by goosetav** [comment]
+1

**Comment by MitinPavel** [comment]
I don’t even know why I would even be against the commit :)
+1

**Comment by jgrevich** [comment]
Does anyone else have commit access other than @yourewelcome ? If not, @yourewelcome , what do you think about electing a few people to help with PRs?

**Comment by cofiem** [comment]
:+1:

**Comment by X0nic** [comment]
:+1:

**Comment by X0nic** [comment]
@jgrevich See issue https://github.com/binarylogic/settingslogic/issues/71

**Comment by X0nic** [comment]
Merged into https://github.com/settingslogic/settingslogic

**Pull request merged**
